language: csharp
mono: none
dotnet: 2.1.403
dist: trusty
services:
  - postgresql
addons:
  postgresql: "9.6"
install:
  - dotnet restore
script:
  - sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" -U postgres
  - dotnet build
  - find test/ -maxdepth 4 -name "*Tests.csproj" -type f -print0 | xargs -0 -L1 dotnet test --no-build
...
